version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: node:8.5.0

    steps:
      - checkout
      - restore_cache:
          key: Nina-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install MongoDB
          command: |
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
            echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 main" | tee /etc/apt/sources.list.d/mongodb-org-3.4.list
            apt-get update
            apt-get install -y mongodb-org-server
            mkdir -p /data/db
            mongod
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Test
          command: yarn test
      - save_cache:
          key: Nina-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
      - add_ssh_keys:
          fingerprints:
            - "1d:58:3c:f7:c0:bb:84:e9:27:85:aa:2e:0c:21:b5:9c"
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == 'master' ]; then
              echo 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $*' > /tmp/ssh
              chmod +x /tmp/ssh
              GIT_SSH=/tmp/ssh git clone ssh://git@ssh.github.com:443/pine/Nina-Private.git /tmp/private

              cp /tmp/private/config/production.js config/
              git config user.name "Pine Mizune"
              git config user.email "pinemz@gmail.com"
              git add config/production.js
              git commit -m "feat(config): add production config"

              bash .circleci/setup-heroku.sh
              git push -f heroku master
            fi
